ALTER TABLE users ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ NULL;

UPDATE users
SET active = CASE WHEN status = 'inactive' THEN FALSE ELSE TRUE END
WHERE active IS NULL;

ALTER TABLE users DROP COLUMN IF EXISTS status;
ALTER TABLE users DROP COLUMN IF EXISTS created_by;
ALTER TABLE users DROP COLUMN IF EXISTS updated_by;

DROP INDEX IF EXISTS idx_users_status;
CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users (deleted_at);
